### ISSUE TITLE
bad order with short values

### ISSUE THREAD

**Issue by oprogramador** [redealumni/i18n_yaml_sorter#12]
The following input:
```yaml
foo:
  grapes: foo
  apples: a
  bananas: bar
```
gives the following output:
```yaml
foo:
  bananas: bar
  grapes: foo
  apples: a
```

However for the following input:
```yaml
foo:
  grapes: foo
  apples: aa
  bananas: bar
```
it sorts correctly.

Another example:
```yaml
foo:
  foo: 1
  bar: 2
```
gives the same output as the input.
