### ISSUE TITLE
Sort is removing references?

### ISSUE THREAD

**Issue by Frexuz** [redealumni/i18n_yaml_sorter#13]
Before saving a file: (reusing stuff with ***blank**)
```
  activerecord:
    errors:
      common:
        blank: &blank can't be blank
      models:
        company:
          attributes:
            subdomain:
              invalid_subdomain: can only contain letters and numbers
        department:
          attributes:
            parent_id:
              cant_be_self: can't be itself
        employee_field:
          column_type:
            invalid_column_type: is an invalid type
        salary:
          attributes:
            amount:
              greater_than: must greater than 0
            signature:
              add_your_esignature: please add your eSignature first
        vacation:
          attributes:
            reason:
              blank: *blank
            rejected_reason:
              blank: *blank
            signature:
              add_your_esignature: please add your eSignature first
        onboarding_task:
          attributes:
            title:
              blank: *blank
            description:
              blank: *blank
            external_url:
              blank: *blank
```

After saving, and the sorter runs from **Guard**, the file becomes: 

```
  activerecord:
    errors:
      common:
        blank: can't be blank
      models:
        company:
          attributes:
            subdomain:
              invalid_subdomain: can only contain letters and numbers
        department:
          attributes:
            parent_id:
              cant_be_self: can't be itself
        employee_field:
          column_type:
            invalid_column_type: is an invalid type
        onboarding_task:
          attributes:
            description:
              blank: can't be blank
            external_url:
              blank: can't be blank
            title:
              blank: can't be blank
        salary:
          attributes:
            amount:
              greater_than: must greater than 0
            signature:
              add_your_esignature: please add your eSignature first
        vacation:
          attributes:
            reason:
              blank: can't be blank
            rejected_reason:
              blank: can't be blank
            signature:
              add_your_esignature: please add your eSignature first
```

Guardfile

```
guard :yamlsort do
  watch(%r{^config/locales/.+\.yml})
end
```

Using `i18n_yaml_sorter (0.2.0)`
