### ISSUE TITLE
Ony appears to work on top two levels

### ISSUE THREAD

**Issue by timhughes** [redealumni/i18n_yaml_sorter#16]
Versions:
  i18n_yaml_sorter: 0.2.0
  ruby: 2.5.3

```
[tim@localhost ~] $ cat foo.yaml
---

key1:
  key1_sub3:
    2: 2
    3: 3
    1: 1
  key1_sub1:
    a: a
    b: b
    c: c
  key1_sub2:
    x: x
    'z': z
    y: y
key3:
  key3_sub1:
    q: q
    p: 'p'
    r: r
key2:
  key2_sub2:
    1: '1'
    3: 3
    2: '2'
  key2_sub1:
    'i': 'i'
    j: j
    k: k

[tim@localhost ~] $ bundle exec sort_yaml < foo.yaml 
---
key1:
  key1_sub1:
    a: a
    b: b
    c: c
  key1_sub2:
    x: x
    'z': z
    y: y
  key1_sub3:
    2: 2
    3: 3
    1: 1
key2:
  key2_sub1:
    'i': 'i'
    j: j
    k: k
  key2_sub2:
    1: '1'
    3: 3
    2: '2'
key3:
  key3_sub1:
    q: q
    p: 'p'
    r: r
```
