### ISSUE TITLE
Keys with slashes are being sorted incorrectly

### ISSUE THREAD

**Issue by buccolo** [redealumni/i18n_yaml_sorter#8]
Hey,

Just a heads up, I noticed that the following yaml:

``` yaml
en:
  activemodel:
    attributes:
      aaa:
        name: Title
      bbb/ccc/ddd:
        countries: Countries / Regions you ship to
```

Is being ordered like this:

``` diff
en:
   activemodel:
     attributes:
       aaa:
+        countries: Countries / Regions you ship to
         name: Title
       bbb/ccc/ddd:
-        countries: Countries / Regions you ship to
```

Thanks for the gem!
